language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get install -qq python-scipy
    - pip install --use-mirrors --upgrade coverage scipy
    - pip freeze

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: nosetests
