language: python

python:
  - "2.7"

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update -q
    - sudo apt-get -y install -q gfortran libblas-dev liblapack-dev libatlas-dev swig    
    - sudo apt-get install -qq python-scipy
    - pip freeze

# command to install dependencies
install:
    - yes w | pip install -q numpy
    - "pip install -r requirements.txt"
    - - python setup.py build_ext --inplace

# command to run tests
script: nosetests
