language: python

os:
  - linux
  # - osx

python:
    - 2.7
    - 3.5

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.

    matrix:
        # Try all python versions with the latest numpy
        #- SETUP_CMD='test'

before_install:
    #-- pull down conda, setup, activate
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; fi

    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"

    #-- config
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    #-- create test environment
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # If there are matplotlib tests, comment these out to
    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
  - conda install -y astropy numpy scipy numba>=0.24.0 llvmlite>=0.9.0 nose pip six

script:
   - python setup.py install
   - nosetests

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    #- if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='astroimtools/tests/coveragerc'; fi
