language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - deps='pip numpy scipy astropy matplotlib cython nose six'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  # install your own package into the environment
  - python setup.py build_ext --inplace

script: nosetests
