language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq gfortran libblas-dev liblapack-dev libatlas-dev swig    
    - pip freeze

# command to install dependencies
install:
    - pip install -q numpy
    - pip install -q scipy 
    - "pip install -r requirements.txt"

# command to run tests
script: nosetests
